#include <iostream>
#include <vector>
using namespace std;

// lecture 31 

// Q 1 . given 'n' range 1 to 1e6, print numbers in increasing
//       order from 1 to n without using loop.
/*
void f(int n){
    if(n<1){
        return ;
    }
    f(n-1);
    cout<<n<<"  ";
}

int main(){
    int n;
    cin>>n;
    f(n);
return 0;
}
*/

//Q 2 . input num=12 , k=5 , print k times multiple of num.
/*
void f(int num,int k){
    if(k==0){
        return ;
    }
    f(num,k-1);
    cout<<num*k<<"  ";
}

int main(){
    int num=12;
    int k=5;

    f(num,k);
return 0;
}
*/

// Q 3 . find the sum of n natural numbers with alterntive sign.
//  input=5 -> 1-2+3-4+5 = 3  output=3
/*
int  f(int n){
    if(n==1){
        return 1;
    }
    return f(n-1) + ((n%2==0)? -n:n);
    
}

int main(){
    int n;
    cin>>n;
    cout<<f(n);
return 0;
}
*/


// lecture 32 :

// Q 1 . find out the gcd (greatest common divisor or HCF) of two no. a and b using recursion.

/*
int f(int a,int b){
    if(b==0){
        return a;
    }
    return f(b,a%b);
}

int main(){
    int a,b;
    cin>>a>>b;
    if (a>b){
        cout<<f(a,b);    
    }else{
        cout<<f(b,a);
    }

return 0;
}
*/

// Q 2 .given a num n . print if it is an armstrong number or not .
/*
int power_rec(int a,int b){
    if(b==0)return 1;
    if(b%2==0){
        int result=power_rec(a,b/2);
        return result * result;

    }else{
        int result = power_rec(a,(b-1)/2);
        return a * result*result;
    }
}

int f(int n,int x){
    if(n==0){
        return 0;
    }
    return power_rec(n%10,x) + f(n/10,x);
}

int main(){
    int n,numOfDigit=0;
    cin>>n;
    int temp=n;

    while(temp>0){
        temp=temp/10;
        numOfDigit++;
    }
    int result=f(n,numOfDigit);
    cout<<((result==n)? true:false);
    
return 0;
}
*/

// Q 3. frog jump in stones , want to go last stone , it jump 1 to 2 or 1 to 3.
//      each stone has costvalue . find way to get minimum cost.
/*
int f(int *arr,int idx,int x){
    
    if(idx == x-1){ 
        return 0;
    }
    if(idx==x-2){
        return f(arr,idx+1,x) + abs(arr[idx]-arr[idx+1]);
    }

    return min(abs(arr[idx+2]-arr[idx]) + f(arr,idx+2,x),abs(arr[idx+1]-arr[idx]) + f(arr,idx+1,x));
 
}

int main(){
        int sizeofarr=4,idx=0;
        
        
       int arr[]={10,30,40,20}; // hight of i th stone
       int cost= f(arr,idx,sizeofarr);
       cout<<cost<<endl;
    return 0;
    }
*/

//lecture 33

// Q 1, find that x is present in array or not;
/*
bool f(int *arr,int i,int n,int x){
    if(i==n){
        return false;
    }
  //  if(arr[i]==x){
  //      return true;
  //  }
    return (((arr[i]==x)? true:false) || f(arr,i+1,n,x));
}

int main(){
    int arr[]={0,1,2,3,4,5,6,7,8,9};
    int x,n=10;
    cin>>x;
    cout<<f(arr,0,n,x);
return 0;
}
*/

// Q 2 .given an array , print sums of all subsets in it, output sum can be print in any order.
// input= arr[]={2,3} output= 0 2 3 5
/*
void f(int *arr,int i,int sum, int n,vector<int> &result){
    //base case
    if(i==n){
        result.push_back(sum);
    return;
    }
    //assumtion

    f(arr,i+1,sum+arr[i],n,result);// picked ith element
    f(arr,i+1,sum,n,result);       // didn't pick ith element
//self work is to store sum in vector 'result' .
}

int main(){
    vector<int>result;    
    int arr[]={2,4,5};
    int n=3;
    f(arr,0,0,n,result);
    for(int i=0;i<result.size();i++){
        cout<<result[i]<<" ";
    }
return 0;
} 
*/

// Q 3. count all possible paths on an m x n grid from top left to bottom right.

/*
int f(int i, int j, int m, int n) {
    if (i == m - 1 && j == n - 1) return 1;
    if (i >= m || j >= n) return 0;
    return f(i + 1, j, m, n) + f(i, j + 1, m, n);
}

int main() {
    cout << f(0, 0, 2, 3);
    return 0;
}
*/

// lecture 34:

// Q 1. given a string, we have to find out all its subsequences of it. a string is a subsequences of a given string,
//      that is generated by deleting some character of a given without changing its order.
// input : abc   output : a,b,c,ab,ac,bc,abc
/*
void f(string &str ,int i,string result ,vector<string> &li){
    if ( i==str.length() ){
        li.push_back(result);
        return;
    }
    f(str,i+1,result+str[i],li);
    f(str,i+1,result,li);  
}
int main(){
    string str="abc";
    string result="";
    vector<string>li;
    f(str,0,result,li);
    for(int i=0;i<li.size();i++){
        cout<<li[i]<<" ";
    }

    return 0;
}
*/

// Q 2. given a string containing digits from 2-9 inclusive, return all posible letter combinations that
//       the number could represent. return the answer in any order.

void f(string &str,int i,string result ,vector<string> &li,vector<string>&v){
    if ( i==str.length() ){
        li.push_back(result);
        return;
    }
    int digit = str[i]-'0';
    if(digit<=1){
        f(str,i+1,result,li,v);
        return;
    }
    for(int j=0;j<v[digit].size();j++){
    f(str,i+1,result+v[digit][j],li,v);
}
    return;
}
int main(){ 
    vector<string>v(10);
    v={"","","abc","def","ghi","jkl","mno","pqrs","tuv","wxyz"};
    string str="423";
    vector<string>li;
    f(str,0,"",li,v);
    for(int i=0;i<li.size();i++){
        cout<<li[i]<<" ";
    }

    return 0;
}